name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - id: changes
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        with:
          filters: |
            workflows:
              - '.github/workflows/**'
      - if: steps.changes.outputs.workflows == 'true'
        uses: docker://rhysd/actionlint:1.7.12@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667
        with:
          args: -color

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - id: changes
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        with:
          filters: |
            ts:
              - '**/*.ts'
              - 'tsconfig.json'
              - 'package.json'
              - 'bun.lock'
      - if: steps.changes.outputs.ts == 'true'
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: latest
      - if: steps.changes.outputs.ts == 'true'
        run: bun install --frozen-lockfile
      - if: steps.changes.outputs.ts == 'true'
        run: bunx tsc --noEmit

  biome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - id: changes
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        with:
          filters: |
            src:
              - '**/*.ts'
              - '**/*.json'
              - 'biome.json'
      - if: steps.changes.outputs.src == 'true'
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: latest
      - if: steps.changes.outputs.src == 'true'
        run: bun install --frozen-lockfile
      - if: steps.changes.outputs.src == 'true'
        run: bunx biome ci .

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - id: changes
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        with:
          filters: |
            docker:
              - 'Dockerfile'
              - '.dockerignore'
      - if: steps.changes.outputs.docker == 'true'
        uses: docker://hadolint/hadolint:v2.14.0-alpine@sha256:7aba693c1442eb31c0b015c129697cb3b6cb7da589d85c7562f9deb435a6657c
        with:
          args: hadolint --failure-threshold warning Dockerfile
